### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown Entity bean class with eclipselink in tomcat 10

### ISSUE THREAD

**Issue by suhail-1997** [apache/tomcat-jakartaee-migration#25] opened 2022-04-07 09:09 UTC
Im trying to upgrade spring web app to tomcat 10 for the upgrade im using apache jakarta migration tool. the application got successfully migrated using this tool but when i run the application in tomcat 10 im facing following issue

java.lang.IllegalArgumentException: Unknown Entity bean class please verify that this class has been marked with the @Entity annotation.

and tables are not being created in the database.

when i run same application in tomcat 9 the tables are being created and i dont face any exception there.

i cant able to figure what is the problem in tomcat 10 even after using migration tool.

**Comment by markt-asf** [comment] 2022-07-05 13:19
There is insufficient information in this issue for it to be investigated. A test case that demonstrates the issue is required. Without such a test case, this issue will eventually be closed.

**Comment by aooohan** [comment] 2022-08-31 10:04
Close this issue first, then reopen it when you have provided a test case.

**Closed by aooohan** 2022-08-31 10:04 UTC
