### ISSUE TITLE
"java.util.zip.ZipException: invalid entry size (expected 0 but got 913 bytes)" when opening migrated jar with `java.util.zip.ZipInputStream`

### ISSUE THREAD

**Issue by hungvietnguyen** [apache/tomcat-jakartaee-migration#46] opened 2023-04-17 16:29 UTC
### Context

I'm investigating https://youtrack.jetbrains.com/issue/KT-57767 where the build fails when reading 
[tomcat-embed-core-10.1.7-jakartaee.jar](https://github.com/apache/tomcat-jakartaee-migration/files/11252858/tomcat-embed-core-10.1.7-jakartaee.zip)

*(Note: If you download the above file, you'll get a `.zip` file because GitHub doesn't accept uploading `.jar`s so I had to rename it to `.zip`.)*

That jar was converted from [tomcat-embed-core-10.1.7.jar](https://repo1.maven.org/maven2/org/apache/tomcat/embed/tomcat-embed-core/10.1.7/tomcat-embed-core-10.1.7.jar) by the [Gradle Jakarta EE Migration plugin](https://github.com/nebula-plugins/gradle-jakartaee-migration-plugin), which uses the [Apache Tomcat migration tool for Jakarta EE](https://github.com/apache/tomcat-jakartaee-migration).

If I open the migrated jar using [java.util.zip.ZipInputStream](http://www.java2s.com/Tutorial/Java/0180__File/UnzipusingtheZipInputStream.htm), I'll get: 
```
java.util.zip.ZipException: invalid entry size (expected 0 but got 913 bytes)
```

If I open it using [java.util.zip.ZipFile](https://jenkov.com/tutorials/java-zip/zipfile.html), I'll get:
```
java.util.zip.ZipException: invalid CEN header (bad signature)
```

This suggests that there is a bug in either `ZipInputStream` (e.g., https://bugs.openjdk.org/browse/JDK-8298530), `ZipFile`, the `tomcat-jakartaee-migration` tool, or a combination of them.

### Request

Please investigate whether this is a bug in the `tomcat-jakartaee-migration` tool.

Even if it isn't, it would still be nice to change the way the tool generates migrated jars such that they can be read by `ZipInpuStream` or `ZipFile` API.

**Comment by markt-asf** [comment] 2023-04-17 17:03
Tomcat 10.1.x already uses the Jakarta EE APIs so there is no need to run a conversion tool on this JAR.

**Comment by ebourg** [comment] 2023-04-17 17:17
I have been able to reproduce the issue. Even if Tomcat 10.1 doesn't need to be migrated the use of a zip64 entry is questionable. The same issue could affect another jar unrelated to Tomcat.

**Comment by ebourg** [comment] 2023-04-17 17:19
I tried disabling the zip64 mode and the migration fails with:

```
Exception in thread "main" org.apache.tomcat.jakartaee.commons.compress.archivers.zip.Zip64RequiredException: Archive's size exceeds the limit of 4GByte.
        at org.apache.tomcat.jakartaee.commons.compress.archivers.zip.ZipArchiveOutputStream.createCentralFileHeader(ZipArchiveOutputStream.java:766)
        at org.apache.tomcat.jakartaee.commons.compress.archivers.zip.ZipArchiveOutputStream.writeCentralDirectoryInChunks(ZipArchiveOutputStream.java:1792)
        at org.apache.tomcat.jakartaee.commons.compress.archivers.zip.ZipArchiveOutputStream.finish(ZipArchiveOutputStream.java:1031)
        at org.apache.tomcat.jakartaee.commons.compress.archivers.zip.ZipArchiveOutputStream.close(ZipArchiveOutputStream.java:633)
        at org.apache.tomcat.jakartaee.Migration.migrateArchiveStreaming(Migration.java:323)
        at org.apache.tomcat.jakartaee.Migration.migrateStream(Migration.java:383)
        at org.apache.tomcat.jakartaee.Migration.migrateFile(Migration.java:274)
        at org.apache.tomcat.jakartaee.Migration.execute(Migration.java:241)
        at org.apache.tomcat.jakartaee.MigrationCLI.main(MigrationCLI.java:107)
```

It smells like a bug in commons-compress.

**Comment by markt-asf** [comment] 2023-04-18 08:29
Use -zipInMemory to avoid this error. I need to remind myself what it was about some zips that meant we needed to introduce this option.

**Comment by ebourg** [comment] 2023-04-18 10:32
I think that was for performance. Maybe we should make it the default when processing jar files.

**Comment by ebourg** [comment] 2023-04-18 12:31
The file is unreadable using a ZipInputStream with OpenJDK 11.0.18 and 17.0.6 (tested with ZuluJDK on Windows). Are you sure it works with Java 11?

I agree this is a JDK bug and we could ignore it if this was fixed in a recent JDK. But until a fix is available the tool is altering a working jar such that no JRE can use it, so I think the burden is upon us to find a solution. At least, if the conditions leading to this issue can be identified, the tool could stop and display a warning, suggesting to use `-zipInMemory`.

I won't reopen the issue because I don't have the time to investigate further, but if someone is willing to contribute a fix I'll certainly review it.

**Comment by markt-asf** [comment] 2023-04-18 12:43
I was testing `ZipFile` which fails with Java 8 but works with Java 11.

I do see issues with `ZipInputStream`. It is failing on the very first entry and in Java code so debugging looks to be possible. I'll take a quick look.

**Comment by ebourg** [comment] 2023-04-18 13:42
If that helps, this is the difference between the two jar files for the first entry (as seen by diffoscope):

```
¦  End-of-central-directory record:
¦  -------------------------------
¦
¦ -  Zip archive file size:                   3406225 (000000000033F991h)
¦ -  Actual end-cent-dir record offset:       3406203 (000000000033F97Bh)
¦ -  Expected end-cent-dir record offset:     3406203 (000000000033F97Bh)
¦ +  Zip archive file size:                   3450535 (000000000034A6A7h)
¦ +  Actual end-cent-dir record offset:       3450437 (000000000034A645h)
¦ +  Expected end-cent-dir record offset:     3450437 (000000000034A645h)
¦    (based on the length of the central directory and its expected offset)
¦
¦    This zipfile constitutes the sole disk of a single-part archive; its
¦    central directory contains 1580 entries.
¦ -  The central directory is 158714 (0000000000026BFAh) bytes long,
¦ +  The central directory is 165034 (00000000000284AAh) bytes long,
¦    and its (expected) offset in bytes from the beginning of the zipfile
¦ -  is 3247489 (0000000000318D81h).
¦ +  is 3285403 (000000000032219Bh).
¦
¦
¦  Central directory entry #1:
¦  ---------------------------
¦
¦    META-INF/native-image/org.apache.tomcat.embed/tomcat-embed-core/native-image.properties
¦
¦    offset of local header from start of archive:   0
¦                                                    (0000000000000000h) bytes
¦ -  file system or operating system of origin:      Unix
¦ -  version of encoding software:                   2.0
¦ +  file system or operating system of origin:      MS-DOS, OS/2 or NT FAT
¦ +  version of encoding software:                   4.5
¦    minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
¦ -  minimum software version required to extract:   1.0
¦ +  minimum software version required to extract:   4.5
¦    compression method:                             deflated
¦    compression sub-type (deflation):               normal
¦    file security status:                           not encrypted
¦ -  extended local header:                          no
¦ +  extended local header:                          yes
¦    file last modified on (DOS date/time):          2023 Feb 27 20:25:28
¦    32-bit CRC value (hex):                         02f543c3
¦    compressed size:                                514 bytes
¦    uncompressed size:                              913 bytes
¦    length of filename:                             87 characters
¦ -  length of extra field:                          0 bytes
¦ +  length of extra field:                          4 bytes
¦    length of file comment:                         0 characters
¦    disk number on which file begins:               disk 1
¦    apparent file type:                             binary
¦ -  Unix file attributes (100644 octal):            -rw-r--r--
¦ +  non-MSDOS external file attributes:             000000 hex
¦    MS-DOS file attributes (00 hex):                none
¦
¦ +  The central-directory extra field contains:
¦ +  - A subfield with ID 0x0001 (PKWARE 64-bit sizes) and 0 data bytes.
¦ +
¦    There is no file comment.
```

**Comment by ebourg** [comment] 2023-04-18 13:51
Something weird I noticed, commons-compress thinks the entries of the original jar have the zip64 field (`ZipArchiveOutputStream.hasZip64Extra()` returns true), and the field is copied to the output jar. But diffoscope doesn't see the extra field on the original jar. I haven't traced back the commons-compress code to understand why.

**Comment by ebourg** [comment] 2023-04-18 14:20
In `Migration.migrateArchiveStreaming()`, if the zip64 field is removed with `destZipEntry.removeExtraField(new ZipShort(0x0001));` the file generated becomes parseable by ZipInputStream. And curiously, commons-compress still sees a zip64 extra field.

**Comment by markt-asf** [comment] 2023-04-18 14:33
Interesting. My debugging was focused on the Data Descriptor. The uncompressed length there is set to 0 for each entry which was triggering the failure for `ZipInputStream`. That seems to be related to Compress's `ZipArchiveEntry` shadowing the `size` field from `ZipEntry` although the debugger is showing some strangeness I don't yet fully understand.

It looks like you have identified a work-around for this issue and we should implement that as any fix in Compress is going to take a while.

Having got this far with Compress I want to keep digging for a little longer.

**Comment by markt-asf** [comment] 2023-04-18 16:31
It is the JRE that is in the wrong: https://bugs.openjdk.org/browse/JDK-8303866

**Comment by eirbjo** [comment] 2023-04-18 16:44
> It is the JRE that is in the wrong: https://bugs.openjdk.org/browse/JDK-8303866

Hi. I contributted JDK-8303866 and the associated PR which is currently under review. Since the PR is so far not approved, I cannot promise that this will be solved or even accepted as a problem. I do hope it will, though.

I would be interested to learn more about which type of tool or API which created this file with ZIP64 data descriptors for small files. It was definitely not `ZipOutputStream`, so then what?

**Comment by eirbjo** [comment] 2023-04-18 16:46
Another exotic feature of this ZIP is that it has CEN ZIP64 extended information fields with no content (0 bytes). I don't think I've ever seen that before.

**Comment by eirbjo** [comment] 2023-04-18 17:37
There is something funny going on with the source file being migrated here, [tomcat-embed-core-10.1.7.jar](https://repo1.maven.org/maven2/org/apache/tomcat/embed/tomcat-embed-core/10.1.7/tomcat-embed-core-10.1.7.jar)

`zipdetails` reports `UNEXPECTED PADDING`:

```
% zipdetails tomcat-embed-core-10.1.7.jar
000000 LOCAL HEADER #1       04034B50
000004 Extract Zip Spec      0A '1.0'
000005 Extract OS            00 'MS-DOS'
000006 General Purpose Flag  0800
       [Bits 1-2]            0 'Normal Compression'
       [Bit 11]              1 'Language Encoding'
000008 Compression Method    0008 'Deflated'
00000A Last Mod Time         565BA32E 'Mon Feb 27 20:25:28 2023'
00000E CRC                   02F543C3
000012 Compressed Length     00000202
000016 Uncompressed Length   00000391
00001A Filename Length       0057
00001C Extra Length          0014
00001E Filename              'META-INF/native-
                             image/org.apache.tomcat.embed/tomcat-
                             embed-core/native-image.properties'
000075 Extra ID #0001        0001 'ZIP64'
000077   Length              0010
000079 PAYLOAD
00027B UNEXPECTED PADDING    ....,.~,./.x....

00028B LOCAL HEADER #2       04034B50
```

**Comment by ebourg** [comment] 2023-04-18 17:44
zipdetails 2.104 gives me a different output:

```
000000 LOCAL HEADER #1       04034B50
000004 Extract Zip Spec      0A '1.0'
000005 Extract OS            00 'MS-DOS'
000006 General Purpose Flag  0800
       [Bits 1-2]            0 'Normal Compression'
       [Bit 11]              1 'Language Encoding'
000008 Compression Method    0008 'Deflated'
00000A Last Mod Time         565BA32E 'Mon Feb 27 21:25:28 2023'
00000E CRC                   02F543C3
000012 Compressed Length     00000202
000016 Uncompressed Length   00000391
00001A Filename Length       0057
00001C Extra Length          0014
00001E Filename              'META-INF/native-
                             image/org.apache.tomcat.embed/tomcat-
                             embed-core/native-image.properties'
000075 Extra ID #0001        0001 'ZIP64'
000077   Length              0010
000079   Uncompressed Size   0000000000000391
000081   Compressed Size     0000000000000202
000089 PAYLOAD

00028B LOCAL HEADER #2       04034B50
```

**Comment by ChristopherSchultz** [comment] 2023-04-18 17:56
I'm happy to have this investigated if it improves our migration tool, but I'm curious as to why the tomcat-embed-10.1.7.jar file is even being migrated. That library should _already_ be using Jakarta EE packages and should not need such migration.

**Comment by eirbjo** [comment] 2023-04-18 17:58
From the OpenJDK side it would be interesting to learn which tool or API produced the `tomcat-embed-10.1.7.jar` file.

**Comment by ChristopherSchultz** [comment] 2023-04-18 18:09
The code is on GH, here: https://github.com/apache/tomcat-jakartaee-migration/blob/main/src/main/java/org/apache/tomcat/jakartaee/Migration.java

Look for `migrateStream`. It's using [commons-compress](https://commons.apache.org/proper/commons-compress/).

**Comment by ebourg** [comment] 2023-04-18 18:10
> From the OpenJDK side it would be interesting to learn which tool or API produced the tomcat-embed-10.1.7.jar file.

It was produced by Ant, which has its own zip implementation closely related to Commons Compress

https://github.com/apache/ant/tree/master/src/main/org/apache/tools/zip

**Comment by markt-asf** [comment] 2023-04-18 18:33
It is also post-processed by BND.

**Comment by eirbjo** [comment] 2023-04-18 18:58
> It is also post-processed by BND.

Commenting out the `add-graal` call makes the ZIP64 extra fields disappear. I have debugged the `zip` call, and `zip` in this case does indeed add the ZIP64 extra fields. This desicion is make in `ZipOutputStream.shouldAddZip64Extra`:

https://github.com/apache/ant/blob/master/src/main/org/apache/tools/zip/ZipOutputStream.java#L846

It hits the last case which is that the `ZipEntry` size is -1 (unknown), the `ZipOutputStream` is writing to a `RandomAccessFile` and the configured mode is not `Zip64Mode.Never`

If Tomcat does not want to produce such files, you could always overide the `zip64Mode` option to `never`, instead of the default `as-needed`.

**Comment by ebourg** [comment] 2023-04-18 19:10
Could this be summarized to Java inhability to read zip files using ZIP64 fields and streaming data headers? If so, this means tomcat-jakartaee-migration could simply detect the ZIP64 extra field and either stop with an error, or enable the in memory processing automatically.

**Comment by eirbjo** [comment] 2023-04-18 19:16
> Could this be summarized to Java inability to read zip files using ZIP64 fields and streaming data headers?

That sounds right. `java.util.ZipInputStream` currently can read 8-byte size fields from the data descriptor record, but only does so when the actual number of compressed or uncompressed files is larger than Integer.MAX_VALUE. My OpenJDK PR changes this to also add a for the precense of a ZIP64 extended information field in the LOC header. If this is present, the Data Descriptor will be read with 8-byte fields. 

> If so, this means tomcat-jakartaee-migration could simply detect the ZIP64 extra field and either stop with an error, or enable the in memory processing automatically.

You are probably reading from files on disk anyway, so perhaps using `java.util.zip.ZipFile` would work better. That API does not need to parse the Data Descriptor record, since it has that all info in the `CEN` headers.
`java.util.zip.ZipInputStream`

**Comment by eirbjo** [comment] 2023-04-18 19:53
> If Tomcat does not want to produce such files, you could always overide the `zip64Mode` option to `never`, instead of the default `as-needed`.

Note that the `jar` task constructor sets the `zip64Mode` to never by default. This explains why the regular `jar` task does not create the ZIP64 entries.

Tomcat could also consider using the `jar` task when updating the jar files with the Graal related files.

**Comment by ebourg** [comment] 2023-04-18 21:19
Digging further... my initial intuition of removing the ZIP64 extra field does really work, I just didn't implement it correctly (I added it only to the STORED branch of `migrateArchiveStreaming`, DEFLATED entries still had the field).

Since the Ant jar task disables ZIP64 fields by default I think `migrateArchiveStreaming` should scrap it (for jar files only). It could check the size of the entry, but a 4GB entry in a jar file seems so unrealistic I'd not bother handling that case.

Side note: Commons Compress is fine, but throws an exception with a misleading message when `zip64mode` is set to `never`:

    Exception in thread "main" org.apache.commons.compress.archivers.zip.Zip64RequiredException: Archive's size exceeds the limit of 4GByte.
            at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.createCentralFileHeader(ZipArchiveOutputStream.java:766)
            at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.writeCentralDirectoryInChunks(ZipArchiveOutputStream.java:1792)
            at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.finish(ZipArchiveOutputStream.java:1031)
            at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.close(ZipArchiveOutputStream.java:633)

This error may appear simply because the entry has a ZIP64 extra field, even when no size limit is exceeded.

**Comment by markt-asf** [comment] 2023-04-18 21:37
Excellent. We can always check if the size > 4GB and log a warning in that case.

**Comment by ebourg** [comment] 2023-04-18 21:50
Suggested fix, test case to follow
https://github.com/ebourg/tomcat-jakartaee-migration/commit/4d8457d3658bff94510e6b215707e172493f0b71

**Comment by markt-asf** [comment] 2023-04-19 07:06
I was also working on a fix. I've combined your fix and mine and committed it. My local test and the unit tests pass.

**Closed by markt-asf** 2023-04-19 07:06 UTC

**Comment by ebourg** [comment] 2023-04-19 07:17
@eirbjo Many thanks for your input, that was really helpful. Good luck with your JDK PR
